spring.application.name=BlogBase
server.port=9999
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_base
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.security.user.name=admin
#spring.security.user.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.ssl.enabled=false

