spring.application.name=BlogBase
server.port=9999
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_base
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.security.user.name=admin
#spring.security.user.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.ssl.enabled=true
server.ssl.key-store=classpath:blogbase-keystore.p12
server.ssl.key-store-password=blogbase
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=blogbase

